### ISSUE TITLE
Help hack Bikepool for SV Bicycle Coalition

### ISSUE THREAD

**Issue by BikeDeputy** [codeforsanjose/Project-Ideas#10]
We know that roughly 60% of people would like to ride a bike more often, but are “concerned,” mostly about their safety in traffic. Increased numbers of bicyclists on the road, particularly in groups of people riding bikes together, can address this concern and create a more inviting, social atmosphere. Bikepool creates a system that brings current and would-be bicycle commuters together in scheduled groups to ride along predetermined routes

We now want to develop a mobile app that will facilitate participation, outreach, and overall functionality of the program.

Desired features of such an app include:
1. Mapping: Show existing routes, suggest nearby routes based on user’s origin/destination, provide real-time arrival and departure information, allow user to suggest future routes.
2. Registration: Allow users to create an account, follow a route or leader, and receive notifications.
3. Messaging/notifications: These might appear on the app or mobile website and/or be pushed to user. Additional features might include gaming aspects such as badges or other prizes.
4. Integration with other apps such as CycleSafe

More info on the SVBC website (http://bikesiliconvalley.org/bikepool/) and in this doc (https://drive.google.com/open?id=0BzYYjemDNhdlcnNXOTc3RE1FOEE). Thanks!

**Comment by BikeDeputy** [comment]
And here's a fresh doc for everyone to collaborate on! https://docs.google.com/document/d/1VXHzUYevh2Rx7djeX8J2prIueN8-MiRIlAfXtajXf6s/edit?usp=sharing

**Comment by BikeDeputy** [comment]
And a shorter link! bit.ly/svbc_bikepoolapp

**Comment by 3vivekb** [comment]
A meetup was held on this topic.  Building of an app just for the Bicycle Coalition has been held off while they test this concept using existing apps.
