### ISSUE TITLE
Map of Silicon Valley development projects

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/Project-Ideas#102]
Catalyze SV is looking to add a map of development projects to our website, perhaps [on this page. ](https://www.catalyzesv.org/projects)

**About Catalyze SV** 
Catalyze SV is engaging community members, developers, and city leaders to envision and create sustainable, equitable, and vibrant places for people in Silicon Valley. Catalyze SV is a  grassroots group aimed at increasing community engagement and support for urban, mixed-use and people-friendly projects across Santa Clara County.

**Data**
Yes, we do have data on the projects. 

The data is often on a City website. Sometimes, Catalyze SV puts some of the info to an excel or Google spreadsheet. 

The public data we have is the permit number, the address, the name of the developer, the broad scope of the project, sometimes the details of the timing/timeframe, sometimes news coverage, sometimes images, etc. 

**Map Features**
Catalyze SV produces action alerts and advocacy letters that we would like to share with stakeholders.

The map could be interactive, yes. At the very least, there would be a small pop up on the same screen to link to more details. 

Overall, what’s really important to our org is to make information about development more accessible and in plain language, as well as let folks know our take as an org.

Perhaps even have the info in Vietnamese and Spanish. 

Here are some local examples of maps showing development: 
- http://missioncity.maps.arcgis.com/apps/MapTour/index.html?appid=5afdbed13fad458cb6288c46a0bad060# 
- https://www.bizjournals.com/sanjose/maps/silicon-valley-crane-watch
- http://thinkbiggersanjose.com/development-information/ 
- https://csj.maps.arcgis.com/apps/webappviewer/index.html?id=ed8cfcd6781c4bddbf97c01cf170dd2a  

**Maintenance** 
We do want to maintain the map and update it regularly, about once a month.  

**Possible Skills needed**
- `mapping`
- `JavaScript, HTML, CSS`
- `working with spreadsheets/CSV/ Google Spreadsheets`
- `data parsing`
- `ux/ui`

**Collaboration**
- Join the discussion on [Slack](https://slackin-c4sj.herokuapp.com/): `#catalyze-sv-map`

Alex Shoor, Catalyze SV Board Member, is open to creative brainstorm with Code for San Jose. 
If you are interested in working on this project, please join the Slack channel and ping Yvonne Pon @pon-y. Yvonne is in touch with Alex.

**Comment by ychoy** [comment]
Lena Tran @lenatran is interested in working on this project

**Comment by pon-y** [comment]
I'm interested in working on this project

**Comment by ychoy** [comment]
Awesome, @lenatran @pon-y feel free to contact Alex Shoor! Also, I added you both to a new channel on our Slack "catalyze-sv-map" where yall can chat more about this project.

**Comment by pon-y** [comment]
Repo can be found here: https://github.com/codeforsanjose/Map-of-Silicon-Valley-development-projects

**Comment by sanazjamloo** [comment]
I'm interested in working on this project as well.  Where can I start?

**Comment by ychoy** [comment]
This project is complete, so closing the issue
