### ISSUE TITLE
WordPress website for nonprofit supporting transition-aged youth 

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/Project-Ideas#103]
Ty Thompson and Dontae Lartigue work with Razing the Bar, a nonprofit focused on supporting transition-aged youth (former foster youth) achieve permanent connections and self-sufficiency.

**Need volunteers to help with**
- Website design 

They are also open to volunteers to help maintain the website after it is designed

**Tools**
Currently the [website](http://razingthebar.org/) is built in WordPress. They are not tied to WordPress, but that is what they are using.
 
If you are interested in volunteering with website design, or have any questions, please join the discussion on our Slack channel: `#website`

I also attached a [one page document](https://github.com/codeforsanjose/Project-Ideas/files/3149477/RTB.One.Pager.pdf) about the nonprofit, Razing the Bar.

**Comment by Kyle-Falconer** [comment]
A couple questions I have off the top of my head:

* What do they have now? (URL to existing website?)
* What would they like changed about what they have now?
* Who on their side would be maintaining or updating the content (if this feature is needed) and what capabilities do they need?

**Comment by ychoy** [comment]
@Kyle-Falconer The website is http://razingthebar.org/

They don't have a lot of content, so I think they're hoping for help with design, layout and building the website. If you need more information, please contact Ty.  

It seems like Ty and Dontae run the nonprofit and would be the people maintaining the website. However, they are open to volunteer maintenance if anyone is interested.

**Comment by ychoy** [comment]
Update - An Nguyen @anguy124 and Julie Roh have started working on this project. To join the discussion and see updates, go to our Code for San Jose Slack channel `#website`. 

An and Julie created a site map and they are planning to read over the information from Razing the Bar. They'll start brainstorming how to organize the information.

**Comment by ychoy** [comment]
This project is complete. You can learn more about it: https://medium.com/code-for-san-jose/redesigning-razing-the-bars-website-b47862bb2efe
