### ISSUE TITLE
Santa Clara County Probation Department website revamp, and/or new digital tools/apps

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforsanjose/Project-Ideas#104]
**Description:**
The Santa Clara County Probation Department wants to engage more youth and families. One of the ways they engage is through the [website](https://www.sccgov.org/sites/probation/), which is currently built on the SharePoint platform. 

They would like an improved user experience for the website and to help users (youth and families) find resources/ answers to questions/ services (e.g. behavior health, getting back to school, tutoring) quickly and easily.

They are also open to getting feedback on other ways of digital engagement, whether through social media, texting, or other communication tools.  

**Collaboration**
Join the conversation and collaborate with team members on Slack channel #scc-probation. To join the Slack, go here https://slackin-c4sj.herokuapp.com/. After you have signed up, go to the #scc-probation channel.

**Comment by ychoy** [comment]
This project is inactive.
