### ISSUE TITLE
Write down use-cases for mountainview.gov

### ISSUE THREAD

**Issue by evankroske** [codeforsanjose/Project-Ideas#14]
Look at mountainview.gov write down a list of things that people might want to do on the website, like find a library book, report a problem to the city, or figure out where they can walk their dogs off-leash.

http://mountainview.gov/

**Comment by arichen** [comment]
Here's open document for this:

https://docs.google.com/document/d/1JZ_-7-g9QRdjgQvX0km94OF-JiiNDqBRJ0sVlNTUCR4/edit?usp=sharing

**Comment by evankroske** [comment]
This project is done! Now, I'd like to get the list translated into HTML:

https://github.com/codeforsanjose/Project-Ideas/issues/39
