### ISSUE TITLE
City of San Jose Draft Open Data Policy

### ISSUE THREAD

**Issue by CSJ-DAT** [codeforsanjose/Project-Ideas#48]
The City of San Jose is committed to freely sharing as much information as possible. We recognize that information is a valuable resource and a strategic asset to the public.  Making information accessible, discoverable, and usable by the public can help fuel entrepreneurship, innovation, scientific discovery, and a more efficient government. 
 
In 2016 the City will launch an open data portal and adopt an open data policy.  Over the next few months, the City will gather community input through a digital survey and a series of public events. 

We appreciate your interest in the City of San Jose’s Draft Open Data Policy.  This is a draft and is subject to further revision.  As part of our commitment to transparency and community engagement, we welcome your interest and feedback on how we can make this policy more effective.  Please send comments or a draft of this document with your suggested revisions to opendata@sanjoseca.gov no later than Friday, December 18th.

If you have questions, please contact Kevin Miller at kevin.miller@sanjoseca.gov.

[Open Data Policy (public).docx](https://github.com/codeforsanjose/Project-Ideas/files/34179/Open.Data.Policy.public.docx)

**Comment by mthong** [comment]
Hey everyone! You can read the policy on Github and provide feedback using the issues tracker or by forking the repo: https://github.com/csj-analytics/csj-open-data-policy

**Comment by mthong** [comment]
Realized it would be a good idea to keep the issue open so that new members will see it and check out the City of San Jose's draft open data policy!
