### ISSUE TITLE
Write script to add latitude and longitude to affordable housing datasets

### ISSUE THREAD

**Issue by evankroske** [codeforsanjose/Project-Ideas#67]
Write a script in Python, Node.js, or another language that does the following:

1. Takes an [affordable housing dataset in CSV format][1].
2. Finds the latitude and longitude of each affordable-housing property using the [Google Maps Geocoding API][2].
3. Produces a CSV file containing the original data plus two new columns containing the latitude and longitude of each property.

Add the script and the augmented datasets to a new directory in [this repository][3].

[1]: http://data.sanjoseca.gov/dataviews/226207/affordable-housing-family-housing/
[2]: http://data.sanjoseca.gov/dataviews/226207/affordable-housing-family-housing/
[3]: https://github.com/codeforsanjose/HackNightProjects

**Comment by evankroske** [comment]
Related to #60

**Comment by KRNelson** [comment]
Got it, submitted pull request.

**Comment by evankroske** [comment]
Merged:

https://github.com/codeforsanjose/HackNightProjects/pull/11
