### ISSUE TITLE
Economic data dashboard/visualization

### ISSUE THREAD

**Issue by BMegas** [codeforsanjose/Project-Ideas#68]
This is something for Chicago: http://howsbusinesschicago.org/

Would be cool to graph http://data.sanjoseca.gov/dashboards/9392/driving-a-strong-local-economy/ and other similar data for San Jose, ideally in such a way as to update automatically and/or feed back to the open data portal for easy visualization. 

Unemployment data is total "labor force" versus number of people working/not working. That's a more complete picture than just a percent unemployment rate. Is the number of unemployed going down, despite an increase in the total working population? 

For housing, it would be cool to see various numbers together, including home prices, housing stock, vacancy rate. Rent vs. own and any indication of how many people are renting out rooms might be another. 

Thanks, Laurie, for getting a start on this on open data day.

**Comment by golgistudio** [comment]
Repo for this started here:

https://github.com/codeforsanjose/economic-indicators-dashboard

**Comment by Kyle-Falconer** [comment]
This has been deployed to production now: http://sjeconomy.com/indicators/#/
