### ISSUE TITLE
"Can I Recycle This?" Image Recognition App

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/Project-Ideas#84]
Create a phone app that allows a user to take a photo of something (E.g. a milk carton) and then returns an answer of whether that item can be recycled in a residential curbside program, based on the address of the user (could be automatically sensed based on location, or entered by user). 

Here's info on what items can and can't be recycled in San Jose. 
https://www.sanjoseca.gov/DocumentCenter/View/23730

If the image recognition software is unable to classify the item or find a match for it in the list of items that can/can't be recycled, it could still provide the user with a list of items based on the above guide. 

Why is this needed? I find it hard to remember whether certain specific items, especially different types of plastic, can be recycled. I bet other people do to!

**Comment by evankroske** [comment]
This is impossible, given the state of technology in 2016.

**Comment by grandecomplex** [comment]
Greetings from the future! Hi, I'm Alex from 2018 in Oakland, CA. @vkaipa and I discussed this today and through the latest image recognition APIs, such from Google, I think this can be possible. Any interest in collaboration? We were thinking of first building it for Oakland, or San Jose I guess why not, and then making it so other data sets can be built and imported.
