### ISSUE TITLE
Web app for DTSJ parking garage status

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/Project-Ideas#85]
Dataset: 
The San Jose open data portal publishes a live feed of available parking spaces in city owned garages in downtown San Jose. The dataset is updated every 5 minutes. 

[http://data.sanjoseca.gov/dataviews/231073/parking-garage-data/](http://data.sanjoseca.gov/dataviews/231073/parking-garage-data/)

Challenge: 
Create a web app that enables users to find out which garages are open and how many spaces are available in each one. 

Bonus points: include a map.

**Comment by toshiru** [comment]
Has this project been initiated? I would love to work on this.

**Comment by bgabot89** [comment]
@toshiru 
I haven't been to Code For SJ in a while due to being busy but the last time I was there, I believe this  project's topic has been changed to issue #86 

You should probably ask the coordinator of that project to see if they can add you as a participant.

**Comment by mthong** [comment]
Hi @toshiru - You are welcome to work on this project! I don't believe it is folded into #86 n- this is a more specific project to do something useful with the parking garage data. 

ParkSJ, the group that operates the City-owned parking garages, has added the table from the data portal to their map, but it isn't the best user interface because the table is separate from the map. 
http://parksj.org/parking-map/

**Comment by toshiru** [comment]
@mthong 

Ok, I'll give this a shot within the next few days.  I have some ideas to improve the UI as well as making it mobile friendly. I'll design a mockup  first and then  perhaps I can recruit a team at the next meet-up. 

Thanks Thomas.
