### ISSUE TITLE
Build a web page that reads data from CSJ's web service and converts it to csv

### ISSUE THREAD

**Issue by artitangri** [codeforsanjose/Project-Ideas#87]
The goal here is to have the data from City of San Jose's web service and make it downloadable in csv format.

An example of the web service data - http://api.sanjoseca.gov/OpenDataService.svc/PlanningPermitsDatas?$format=json&$filter=Status%20eq%20%2730%27 
This returns all the planning permits issued by the city in last 30 days

**Comment by 3vivekb** [comment]
Rolled into #86
